#!/usr/bin/env python3
"""Generate C header from files in assets/.

Scans the `assets/` directory and embeds each file as a gzipped byte array in
`include/generated/assets.h`. This script is intended to be run before build.
"""
import os
import gzip
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = ROOT / "assets"
OUT_DIR = ROOT / "include" / "generated"
OUT_FILE = OUT_DIR / "assets.h"


def sanitize_identifier(rel_path: str) -> str:
    # Convert a relative asset path like 'css/style.css' into a C identifier
    ident = re.sub(r"[^0-9a-zA-Z]+", "_", rel_path)
    ident = ident.strip("_")
    return "asset_" + ident


def make_header(entries):
    hdr = []
    hdr.append("// Auto-generated by scripts/generate_assets.py - DO NOT EDIT")
    hdr.append("#pragma once")
    hdr.append("#include <stdint.h>")
    hdr.append("#include <stddef.h>")
    hdr.append("#include <stdbool.h>")
    hdr.append(
        "struct asset { const char *path; const uint8_t *data; size_t len; size_t gzlen; bool gz; };"
    )
    hdr.append("")
    for name, path, gzdata in entries:
        # name is the web path like '/index.html'
        rel = name.lstrip("/")
        ident = sanitize_identifier(rel)
        hdr.append(f"static const unsigned char {ident}[] = {{")
        # format bytes 12 per line
        bchunks = [f"0x{b:02x}" for b in gzdata]
        for i in range(0, len(bchunks), 12):
            chunk = bchunks[i : i + 12]
            hdr.append("  " + ", ".join(chunk) + ",")
        hdr.append("};")
        hdr.append(f"static const size_t {ident}_len = {len(gzdata)};")
        hdr.append("")

    # assets array
    hdr.append("static const struct asset embedded_assets[] = {")
    for name, path, gzdata in entries:
        rel = name.lstrip("/")
        ident = sanitize_identifier(rel)
        hdr.append(f'  {{"{name}", {ident}, {ident}_len, {ident}_len, true}},')
    hdr.append("};")
    hdr.append(
        "static const size_t embedded_assets_count = sizeof(embedded_assets)/sizeof(embedded_assets[0]);"
    )
    return "\n".join(hdr)


def main():
    entries = []
    for root, dirs, files in os.walk(ASSETS_DIR):
        for f in files:
            p = Path(root) / f
            rel = "/" + str(p.relative_to(ASSETS_DIR)).replace("\\", "/")
            data = p.read_bytes()
            gz = gzip.compress(data, compresslevel=6)
            entries.append((rel, p, gz))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(make_header(entries))
    os.system("clang-format -i " + str(OUT_FILE))
    print(f"Wrote {OUT_FILE} with {len(entries)} assets")


if __name__ == "__main__":
    main()
